area/sdlc:
  - changed-files:
      - any-glob-to-any-file:
          - '.devcontainer/**/*'
          - '.github/**/*'
          - '.pre-commit-config.yaml'
          - '.vscode/**/*'
          - 'poetry.lock'
          - 'pyproject.toml'
          - 'renovate.json'
area/ui:
  - changed-files:
      - any-glob-to-any-file:
          - 'autofeat/ui/**/*'
priority/low:
  - changed-files:
      - any-glob-to-any-file:
          - '**'
