[tool.poetry]
name = "autofeat"
version = "0.1.0"
readme = "README.md"
authors = ["Ashwin Madavan <ashwin.madavan@gmail.com>"]
description = "EDA Automation"

[tool.poetry.dependencies]
python = "^3.11"
polars = "^1.6.0"
kaggle = "^1.6.17"
networkx = "^3.3"
xgboost = "^2.1.1"
llvmlite = "^0.43.0"
numba = "^0.60.0"
shap = "^0.46.0"
scikit-learn = "^1.5.2"
cudf-polars-cu12 = {version = "^24.8.3", source = "nvidia"}

[tool.poetry.group.dev.dependencies]
notebook = "^7.2.2"
pytest = "^8.3.2"
mypy = "^1.11.2"
types-networkx = "^3.2.1.20240907"

[[tool.poetry.source]]
name = "nvidia"
url = "https://pypi.nvidia.com"
priority = "supplemental"
