[tool.poetry]
name = "autofeat"
version = "0.1.0"
readme = "README.md"
authors = ["Ashwin Madavan <ashwin.madavan@gmail.com>"]
description = ""

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.6.0"
kaggle = "^1.6.17"
networkx = "^3.3"
xgboost = "^2.1.1"
llvmlite = "^0.43.0"
numba = "^0.60.0"
shap = "^0.46.0"

[tool.poetry.group.dev.dependencies]
notebook = "^7.2.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
