[tool.poetry]
name = "autofeat"
version = "0.1.0"
readme = "README.md"
authors = ["Ashwin Madavan <ashwin.madavan@gmail.com>"]
description = ""

[tool.poetry.dependencies]
python = "^3.12"
polars = "^1.6.0"
kaggle = "^1.6.17"

[tool.poetry.group.dev.dependencies]
notebook = "^7.2.2"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.2"
