name: ci
on:
  pull_request:
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.1
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: failure()
        with:
          commit_message: Run pre-commit
