name: ci
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.12
          poetry-version: 1.8.3
      - run: poetry run mypy .
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
      - uses: stefanzweifel/git-auto-commit-action@v5
        if: failure()
        with:
          commit_message: 'chore: run pre-commit'
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.12
          poetry-version: 1.8.3
      - run: poetry run pytest -v
