name: ci
on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.11
          poetry-version: 1.8.3
      - run: poetry run mypy .
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - uses: pre-commit/action@v3.0.1
        env:
          SKIP: no-commit-to-branch
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: packetcoders/action-setup-cache-python-poetry@v1.2.0
        with:
          python-version: 3.11
          poetry-version: 1.8.3
      - run: poetry run pytest -v --cov=autofeat --doctest-modules
