name: maintenance
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  github:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout head
        uses: actions/checkout@v4
      - name: Delete old branches
        uses: beatlabs/delete-old-branches-action@v0.0.10
        with:
          repo_token: ${{ github.token }}
          date: '1 week ago'
          dry_run: false
